X_FIELD, Y_FIELD = 550, 550
WIDTH, HEIGHT = 50, 50
GAME_MODE_DEFAULT = 2
GREEN_PLAYER_DEFAULT = True
GREEN_PLAYER_COORDINATE_DEFAULT = ((3-1)*2*HEIGHT, (1-1)*2*WIDTH)
RED_PLAYER_COORDINATE_DEFAULT = ((4-1)*2*HEIGHT, (6-1)*2*WIDTH)